name: AuthLobby
main: net.omniblock.lobbies.auth.AuthLobbyPlugin
softdepend: [OmniNetwork, OmniLobbies]
version: 2.5.0
author: Omniblock Developers Team
website: www.omniblock.net
commands:
   register:
      aliases: [register, r, login, l]
      description: Permite logearse o registrarse en el servidor.